main: aliuly\manyworlds\Main
api:
- 2.0.0
- 1.13.0
load: POSTWORLD

name: World
description: Create many worlds! #MNetwork
version: 1.0.0
author: Sheep

commands:
  manyworlds:
    description: Manage worlds
    usage: "/mw <help|sub-cmd> [options]"
    permission: mw.cmds
    aliases: [mw]

permissions:
  mw.cmds:
    default: true
    description: "Allow all the Worlds functionality"
  mw.cmd.tp:
    default: op
    description: "Allows users to travel to other worlds"
  mw.cmd.tp.others:
    default: op
    description: "Allows users to make others travel to other worlds"
  mw.cmd.ls:
    default: op
    description: "Allows users to list worlds"
  mw.cmd.world.create:
    default: op
    description: "Allows users to create worlds"
  mw.cmd.world.load:
    default: op
    description: "Allows users to load worlds"
  mw.cmd.lvdat:
    default: op
    description: "Manipulate level.dat"
  mw.cmd.default:
    default: op
    description: "Changes default world"
